import {
  Action,
  ActionPanel,
  Clipboard,
  Icon,
  List,
  Toast,
  showToast,
} from "@raycast/api";
import { readFileSync } from "node:fs";
import { homedir } from "node:os";
import { join } from "node:path";

type Bind = { keys: string; action: string };
type Group = { name: string; note?: string; binds: Bind[] };
type Data = { meta?: { title?: string; hyper?: string }; groups: Group[] };

// Generated by the chezmoi run_onchange script from cheatsheet.toml.
const DATA_PATH = join(homedir(), ".local", "state", "helium", "cheatsheet.json");

function load(): Data | null {
  try {
    return JSON.parse(readFileSync(DATA_PATH, "utf8")) as Data;
  } catch {
    return null;
  }
}

// Make the keys string searchable: keep it whole, and also split it into
// tokens so "hyper c" or "close" both match.
function keywordsFor(bind: Bind, group: string): string[] {
  const tokens = `${bind.keys} ${group}`.split(/[\s/+,]+/).filter(Boolean);
  return [bind.keys, ...tokens];
}

export default function Command() {
  const data = load();

  if (!data) {
    return (
      <List>
        <List.EmptyView
          icon={Icon.Warning}
          title="Cheatsheet not generated yet"
          description="Run `just apply` in the Helium repo to build the shortcut data."
        />
      </List>
    );
  }

  const hyper = data.meta?.hyper;

  return (
    <List
      searchBarPlaceholder="Search shortcuts — by action or keys…"
      navigationTitle={data.meta?.title ?? "Helium Shortcuts"}
    >
      {hyper ? (
        <List.Section title="Legend">
          <List.Item
            icon={Icon.Info}
            title="Hyper"
            subtitle={hyper}
            keywords={["hyper", "legend", "modifier"]}
          />
        </List.Section>
      ) : null}

      {data.groups.map((group) => (
        <List.Section
          key={group.name}
          title={group.name}
          subtitle={group.note ? group.note : undefined}
        >
          {group.binds.map((bind, index) => (
            <List.Item
              key={`${group.name}-${index}`}
              icon={Icon.Dot}
              title={bind.action}
              accessories={[{ tag: bind.keys }]}
              keywords={keywordsFor(bind, group.name)}
              actions={
                <ActionPanel>
                  <Action
                    title="Copy Keys"
                    icon={Icon.Clipboard}
                    onAction={async () => {
                      await Clipboard.copy(bind.keys);
                      await showToast({
                        style: Toast.Style.Success,
                        title: "Copied keys",
                        message: bind.keys,
                      });
                    }}
                  />
                  <Action.CopyToClipboard
                    title="Copy Action"
                    content={bind.action}
                    shortcut={{ modifiers: ["cmd", "shift"], key: "c" }}
                  />
                </ActionPanel>
              }
            />
          ))}
        </List.Section>
      ))}
    </List>
  );
}
